# https://www.zigbee2mqtt.io/information/configuration.html
# Required: Home Assistant integration (MQTT discovery) (default: false)
homeassistant: true

# Required: allow new devices to join.
# WARNING: Disable this after all devices have been paired! (default: false)
permit_join: true

# Required: MQTT settings
mqtt:
  # Required: MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
  server: 'mqtt://192.168.1.127:1883'
  # Optional: absolute path to SSL/TLS certificate of CA used to sign server and client certificates (default: nothing)
  ca: '/etc/ssl/mqtt-ca.crt'
  # Optional: absolute paths to SSL/TLS key and certificate for client-authentication (default: nothing)
  key: '/etc/ssl/mqtt-client.key'
  cert: '/etc/ssl/mqtt-client.crt'
  # Optional: MQTT server authentication user (default: nothing)
  user: '!secret user'
  # Optional: MQTT server authentication password (default: nothing)
  password: '!secret password'
  # Optional: MQTT client ID (default: nothing)
  client_id: 'zigb2mqtt'
  # Optional: disable self-signed SSL certificates (default: false)
  reject_unauthorized: true
  # Optional: Include device information to mqtt messages (default: false)
  include_device_information: true
  # Optional: MQTT keepalive in seconds (default: 60)
  keepalive: 60
  # Optional: MQTT protocol version (default: 4), set this to 5 if you
  # use the 'retention' device specific configuration
  version: 4

# Required: serial settings
serial:
  # Required: location of the adapter (e.g. CC2531).
  # To autodetect the port, set 'port: null'.
  port: /dev/cc2531
  # Optional: disable LED of the adapter if supported (default: false)
  disable_led: false
  # Optional: adapter type, not needed unless you are experiencing problems (default: shown below, options: zstack, deconz)
  # adapter: null

advanced:
  # Optional: Logging level, options: debug, info, warn, error (default: info)
  log_level: info
   # Optional: Location of log directory (default: shown below)
  log_directory: data/log/
  # Optional: Log file name, can also contain timestamp, e.g.: zigbee2mqtt_%TIMESTAMP%.log (default: shown below)
  log_file: log_%TIMESTAMP%.txt
  # https://www.zigbee2mqtt.io/how_tos/how_to_secure_network.html
  network_key: '!secret network_key'
  
  
docker run -it -v $(pwd)/data:/app/data --device=/dev/ttyACM0 -e TZ=America/Los_Angeles -v /run/udev:/run/udev:ro --privileged=true koenkk/zigbee2mqtt