# Most services should use Docker labels. Non docker services can go in here. See: https://community.containo.us/t/expose-a-docker-container-without-labels/1907/9

http:
  routers:
    # Define a connection between requests and services
    homeassistant-secure:
      rule: "Host(`home.tylerhovanec.com`)"
      entryPoints:
        - "websecure"
      service: homeassistant # refers to the http.services.homeassistant entry
      tls:
        certResolver: dns-cloudflare

  services:
  # Define how to reach an existing service outside of docker
    homeassistant:
      loadBalancer:
        servers:
        - url: "http://192.168.1.127:8123/"
